language: java
jdk:
  - openjdk8
  
branches:
  only:
    - master
    
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'

script: "mvn clean package"

# CI 실행 완료 시 메일로 알람
notification:
  email:
    recipents:
      - "zero2080@naver.com"

before-deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp target/*.war before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/web-secutiry.zip
  
deploy:
  - provider: s3
    access_key_id: AKIATWG6BDCM2OO7TSPS
    secret_access_key: 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
    bucket: travis-auto-deploy
    region: ap-northeast-2
    skip-cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    
  - provider: codedeploy
    access_key_id: AKIATWG6BDCM2OO7TSPS
    secret_access_key: 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
    bucket: travis-auto-deploy
    key: web-secutiry.zip
    bundle_type: zip
    application: web-security
    deployment_group: web-security-auto-deploy
    region: ap-northeast-2
    wait-until-deploy: true