language: java
jdk:
  - openjdk8
  
branches:
  only:
    - master
    
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'

script: "mvn package"

# CI 실행 완료 시 메일로 알람
notification:
  email:
    recipents:
      - "zero2080@naver.com"

before-deploy:
  - zip -r web-secutiry *
  - mkdir -p deploy
  - mv web-secutiry.zip deploy/web-secutiry.zip
  
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-auto-deploy
    skip-cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true